AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  server to validate arc-gis code
Globals:
  Function:
    MemorySize: 128
    Timeout: 15

Resources:
  # ====== TEST ======
  ValidateArcGisCodeFunctionApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: api
      Cors:
        AllowMethods: "'OPTIONS,GET,POST'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"
  ValidateArcGisCodeFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - 'lambda.amazonaws.com'
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
  ValidateArcGisCodeFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/node/validate-code/
      Handler: app.lambdaHandler
      Runtime: nodejs14.x
      Role: !GetAtt ValidateArcGisCodeFunctionRole.Arn
      Events:
        Compare:
          Type: Api
          Properties:
            Path: /validate
            Method: post
            RestApiId: !Ref ValidateArcGisCodeFunctionApi